name: 📦 Feature Request
description: Request A Feature
title: "👌🏻[IMPROVE]: "
type: "feature"
# labels: ["feature"]
projects: ["CoveredCA/4"]
# assignees:
#   - <GH USERNAME>
body:
  - type: markdown
    attributes:
      value: |
        > Thanks for taking the time to help us improve!

  - type: textarea
    id: related-to-problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: Ex. Currently the app only provides xy funcionality [...]
    validations:
      required: true

  - type: textarea
    id: requested-solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: The app should provide xy AND z functionality because [...]
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: I thought about using [...] solution but it seems like more of a work around than a robust alternative.
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder:
    validations:
      required: false

  - type: checkboxes
    id: agreements
    attributes:
      label: Agreements
      description: By submitting this issue, you agree that you have provided and performed the following
      options:
        - label: I have provided the necessary information about my request
          required: true
        - label: I understand that my issue may be closed if I don't fulfill my promises.
          required: true
        - label: I has added this issue to a milestone in this repository
          required: true
